/*
modal para confirmar a finalização do pedido
 */
package view;

import daobanco.BancoDados;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import static java.util.Objects.isNull;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.*;
import sistema.Algoritmos;
import sistema.JCComboDados;
import sistema.JListDados;

/**
 *
 * @author Salomão Francisco da Silva - Fone: 62 99447-4551
 * @version 1.0
 */
public class JDFinalizaPedido extends javax.swing.JDialog {

    private Pedido compra;
    private List listaDados = new ArrayList();
    private JFrame janela;
    private String valorTotal;

    /**
     * Creates new form JDConfirmarCompra
     */
    public JDFinalizaPedido(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        // carrega os clientes
        carregaClientes();

        // carrega os funcionários
        carregaFuncionarios();

    }

    // seta a compra
    public void setCompra(Pedido compra) {

        this.compra = compra;

    }

    // seta o total
    public void setTotal(String valor) {

        // seta o valor total
        this.valorTotal = valor;
        this.JLTotal.setText(Algoritmos.formataMoeda(valor));
        this.JLTotalDireto.setText(Algoritmos.formataMoeda(valor));

    }

    // carrega os clientes
    private void carregaClientes() {

        JListDados lista = new JListDados("tb_cliente", "nome");
        listaDados = lista.recuperaDados(JLClientes);

    }

    // pesquisa clientes
    private void pesquisarClientes() {

        // valores de pesquisa
        Map colunasPesquisa = new LinkedHashMap();
        colunasPesquisa.put("nome", this.JTNome.getText());

        // pesquisa
        JListDados lista = new JListDados("tb_cliente", "nome");
        listaDados = lista.pesquisaDados(JLClientes, colunasPesquisa);

    }

    // seta a janela
    public void setJanela(JFrame janela) {

        this.janela = janela;

    }

    // carrega funcionários
    public void carregaFuncionarios() {

        JCComboDados lista = new JCComboDados("tb_funcionario", "nome");
        listaDados = lista.recuperaDados(this.JCFuncionario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        JLTotalDireto = new javax.swing.JLabel();
        JBConcluiVendaDireta = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        JTEntradaDireta = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        JLTrocoEntradaDireta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTMesa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JCFuncionario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JTNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLClientes = new javax.swing.JList<>();
        JLCpf = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JBConcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JLTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar pedido");
        setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Total a ser pago R$"));

        JLTotalDireto.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        JLTotalDireto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTotalDireto.setText("0.0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTotalDireto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTotalDireto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JBConcluiVendaDireta.setText("Concluir");
        JBConcluiVendaDireta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConcluiVendaDiretaActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada R$"));

        JTEntradaDireta.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        JTEntradaDireta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTEntradaDireta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTEntradaDiretaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTEntradaDireta)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTEntradaDireta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Troco"));

        JLTrocoEntradaDireta.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        JLTrocoEntradaDireta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTrocoEntradaDireta.setText("R$: 0.0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTrocoEntradaDireta, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTrocoEntradaDireta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBConcluiVendaDireta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBConcluiVendaDireta)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venda no caixa", jPanel1);

        jLabel2.setText("Mesa:");

        jLabel4.setText("Funcionário:");

        jButton1.setText("Concluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCFuncionario, 0, 303, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JCFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comanda", jPanel3);

        JTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTNomeKeyReleased(evt);
            }
        });

        jLabel1.setText("Cliente:");

        JLClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JLClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JLClientes);

        JLCpf.setText("###.###.###-##");

        jLabel3.setText("CPF:");

        JBConcluir.setText("Concluir");
        JBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConcluirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total R$"));

        JLTotal.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        JLTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTotal.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLCpf)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBConcluir))
                        .addGap(0, 84, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JLCpf))
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBConcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entrega", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNomeKeyReleased

        // pesquisa clientes
        pesquisarClientes();

    }//GEN-LAST:event_JTNomeKeyReleased

    private void JLClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JLClientesValueChanged

        // verifica se há um cliente 
        if (this.JLClientes.getSelectedIndex() >= 0) {

            // habilita
            JBConcluir.setEnabled(true);

        } else {

            // desabilita
            JBConcluir.setEnabled(false);

            // dialogo
            Algoritmos.dialogo("Por favor selecione um cliente!");

        }

        // trata excessão
        try {

            // id do cadastro do cliente
            String idCadastroCliente = (String) listaDados.get(this.JLClientes.getSelectedIndex());

            // valida se há um cliente selecionado
            if (isNull(idCadastroCliente) == true) {

                // dialogo
                Algoritmos.dialogo("Por favor selecione um cliente!");

            } else {

                // banco de dados
                BancoDados banco = new BancoDados();
                Map dados = banco.recuperaDadosChavePrimaria("id", idCadastroCliente, "tb_cliente");

                // seta cpf
                this.JLCpf.setText((String) dados.get("cpf"));

                // novo cliente
                Cliente cliente = new Cliente();
                cliente.setCep((String) dados.get("cep"));
                cliente.setCidade((String) dados.get("cidade"));
                cliente.setCpf((String) dados.get("cpf"));
                cliente.setEndereco((String) dados.get("endereco"));
                cliente.setNome((String) dados.get("nome"));
                cliente.setTelefone((String) dados.get("telefone"));
                cliente.setUf((String) dados.get("uf"));

                // seta o cliente
                compra.setCliente(cliente);

            }

        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {

        }

    }//GEN-LAST:event_JLClientesValueChanged

    private void JBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConcluirActionPerformed

        // confirma a venda
        if (JOptionPane.showConfirmDialog(null, "Confirmar venda?") == 0) {

            // seta entrega
            compra.setEntrega();

            // finaliza a compra
            compra.finalizaCompra();

            // fecha a janela de pedidos
            this.janela.dispose();

            // fecha esta janela         
            this.dispose();

        }

    }//GEN-LAST:event_JBConcluirActionPerformed

    private void JTEntradaDiretaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTEntradaDiretaKeyReleased

        // valor total
        Double valor = Algoritmos.ConverteStringDouble(valorTotal);
        Double valorEntrada = Algoritmos.ConverteStringDouble(this.JTEntradaDireta.getText());

        // troco
        Double troco = Algoritmos.arredondaNumero(valorEntrada - valor);

        // seta o troco
        this.JLTrocoEntradaDireta.setText(Algoritmos.formataMoeda(Double.toString(troco)));

    }//GEN-LAST:event_JTEntradaDiretaKeyReleased

    private void JBConcluiVendaDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConcluiVendaDiretaActionPerformed

        // confirma a venda
        if (JOptionPane.showConfirmDialog(null, "Confirmar venda?") == 0) {

            // cliente ficticio
            Cliente cliente = new Cliente();
            cliente.setNome("#caixa");

            // seta o cliente
            compra.setCliente(cliente);

            // seta pagamento
            compra.setPagamentoRealizado();

            // finaliza a compra
            compra.finalizaCompra();

            // fecha a janela de pedidos
            this.janela.dispose();

            // fecha esta janela         
            this.dispose();

        }

    }//GEN-LAST:event_JBConcluiVendaDiretaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // confirma a venda
        if (JOptionPane.showConfirmDialog(null, "Confirmar venda?") == 0) {

            // cliente ficticio
            Cliente cliente = new Cliente();
            cliente.setNome("#comanda");

            // seta o cliente
            compra.setCliente(cliente);

            // seta comanda
            compra.setComanda();
            compra.setComandaFuncionario((String) this.JCFuncionario.getSelectedItem());
            compra.setComandaMesa(this.JTMesa.getText());

            // finaliza a compra
            compra.finalizaCompra();

            // fecha a janela de pedidos
            this.janela.dispose();

            // fecha esta janela         
            this.dispose();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFinalizaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFinalizaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFinalizaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFinalizaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFinalizaPedido dialog = new JDFinalizaPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBConcluiVendaDireta;
    private javax.swing.JButton JBConcluir;
    private javax.swing.JComboBox<String> JCFuncionario;
    private javax.swing.JList<String> JLClientes;
    private javax.swing.JLabel JLCpf;
    private javax.swing.JLabel JLTotal;
    private javax.swing.JLabel JLTotalDireto;
    private javax.swing.JLabel JLTrocoEntradaDireta;
    private javax.swing.JTextField JTEntradaDireta;
    private javax.swing.JTextField JTMesa;
    private javax.swing.JTextField JTNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
